package com.sye.seeing.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sye.seeing.dao.Markdown;

import com.sye.seeing.dao.MarkdownDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig markdownDaoConfig;

    private final MarkdownDao markdownDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        markdownDaoConfig = daoConfigMap.get(MarkdownDao.class).clone();
        markdownDaoConfig.initIdentityScope(type);

        markdownDao = new MarkdownDao(markdownDaoConfig, this);

        registerDao(Markdown.class, markdownDao);
    }
    
    public void clear() {
        markdownDaoConfig.getIdentityScope().clear();
    }

    public MarkdownDao getMarkdownDao() {
        return markdownDao;
    }

}
